FROM ubuntu:18.04

ENV OPENVPN_VERSION=2.4.7
ADD OpenVPN-obfs.patch ./

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y gcc-mingw-w64 gcc-mingw-w64-i686 man2html-base
RUN apt-get install -y git curl unzip autoconf libtool
RUN git clone 'https://github.com/OpenVPN/openvpn-build'
RUN cd openvpn-build/generic/ && \
    cp ../../OpenVPN-obfs.patch ./patches/openvpn-001-obfs.patch && \
    IMAGEROOT=`pwd`/image-win32 \
        CHOST=i686-w64-mingw32 \
        CBUILD=i686-pc-cygwin \
        OPENVPN_VERSION=${OPENVPN_VERSION} \
        ./build && \
    IMAGEROOT=`pwd`/image-win64 \
        CHOST=x86_64-w64-mingw32 \
        CBUILD=i686-pc-cygwin \
        OPENVPN_VERSION=${OPENVPN_VERSION} \
        ./build
				
